name: Generate docs structure

on:
  push:
    branches: ['**']
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  docgen:
    uses: cat-of-summer/git_toolkit/.github/workflows/docgen.yml@main
